import type { CaptionStyle, CaptionTemplateId } from "@/lib/types";

/**
 * Built-in caption aesthetics. Users pick a template, then fine-tune any
 * field in the inspector; the template id keeps the picker highlighted.
 */
export const CAPTION_TEMPLATES: Record<CaptionTemplateId, CaptionStyle> = {
  // Instagram Reels "clean phrase" style: white medium-weight sentence-case
  // phrases in the upper-middle of the frame, thin outline + soft shadow,
  // no per-word highlighting.
  // Calibrated against four creator reels: ~0.031×H font, weight 600,
  // caption block ~22–28% from the top.
  reels: {
    template: "reels",
    fontFamily: "Inter",
    fontSize: 0.031,
    fontWeight: 600,
    karaoke: false,
    animation: "fade",
    uppercase: false,
    textColor: "#ffffff",
    activeColor: "#ffffff",
    activeBgColor: "",
    strokeColor: "#000000",
    strokeWidth: 0.07,
    shadow: true,
    verticalPosition: 0.24,
    maxWordsPerLine: 8,
    highlightKeywords: false,
    accentColor: "#ffd400",
    autoEmoji: false,
  },
  // Seen in the Premiere-plugin reference (spec visible in its UI:
  // "Inter Bold · 64pt · 2 words"): tiny bold bursts dead-center.
  burst: {
    template: "burst",
    fontFamily: "Inter",
    fontSize: 0.033,
    fontWeight: 700,
    karaoke: false,
    animation: "fade",
    uppercase: false,
    textColor: "#ffffff",
    activeColor: "#ffffff",
    activeBgColor: "",
    strokeColor: "#000000",
    strokeWidth: 0.05,
    shadow: true,
    verticalPosition: 0.5,
    maxWordsPerLine: 2,
    highlightKeywords: false,
    accentColor: "#2dd4a0",
    autoEmoji: false,
  },
  hormozi: {
    template: "hormozi",
    fontFamily: "Archivo Black",
    fontSize: 0.042,
    fontWeight: 800,
    karaoke: true,
    animation: "pop",
    uppercase: true,
    textColor: "#ffffff",
    activeColor: "#ffd400",
    activeBgColor: "",
    strokeColor: "#000000",
    strokeWidth: 0.16,
    shadow: true,
    verticalPosition: 0.72,
    maxWordsPerLine: 4,
    highlightKeywords: false,
    accentColor: "#ffd400",
    autoEmoji: false,
  },
  clean: {
    template: "clean",
    fontFamily: "Inter",
    fontSize: 0.034,
    fontWeight: 600,
    karaoke: true,
    animation: "none",
    uppercase: false,
    textColor: "#ffffff",
    activeColor: "#ffffff",
    activeBgColor: "",
    strokeColor: "",
    strokeWidth: 0,
    shadow: true,
    verticalPosition: 0.78,
    maxWordsPerLine: 5,
    highlightKeywords: false,
    accentColor: "#7c5cff",
    autoEmoji: false,
  },
  pop: {
    template: "pop",
    fontFamily: "Archivo Black",
    fontSize: 0.038,
    fontWeight: 800,
    karaoke: true,
    animation: "pop",
    uppercase: true,
    textColor: "#ffffff",
    activeColor: "#0c0e13",
    activeBgColor: "#2dd4a0",
    strokeColor: "#000000",
    strokeWidth: 0.1,
    shadow: false,
    verticalPosition: 0.74,
    maxWordsPerLine: 3,
    highlightKeywords: false,
    accentColor: "#2dd4a0",
    autoEmoji: false,
  },
};

export const TEMPLATE_LABELS: Record<CaptionTemplateId, string> = {
  reels: "Reels Clean",
  burst: "Center Burst",
  hormozi: "Hormozi Bold",
  clean: "Minimal Karaoke",
  pop: "Chip Pop",
};
