import type { CaptionStyle, CaptionTemplateId } from "@/lib/types";

/**
 * Built-in caption aesthetics. Users pick a template, then fine-tune any
 * field in the inspector; the template id keeps the picker highlighted.
 */
export const CAPTION_TEMPLATES: Record<CaptionTemplateId, CaptionStyle> = {
  // Instagram Reels "clean phrase" style: white medium-weight sentence-case
  // phrases in the upper-middle of the frame, thin outline + soft shadow,
  // no per-word highlighting.
  // Calibrated against four creator reels: ~0.031×H font, weight 600,
  // caption block ~22–28% from the top.
  reels: {
    template: "reels",
    fontFamily: "Inter",
    fontSize: 0.042,
    fontWeight: 700,
    karaoke: false,
    animation: "fade",
    uppercase: false,
    textColor: "#ffffff",
    activeColor: "#ffffff",
    activeBgColor: "",
    strokeColor: "#000000",
    strokeWidth: 0.1,
    shadow: true,
    verticalPosition: 0.26,
    maxWordsPerLine: 6,
    highlightKeywords: false,
    accentColor: "#ffd400",
    autoEmoji: false,
    twoTone: false,
    boxColor: "",
  },
  // Seen in the Premiere-plugin reference (spec visible in its UI:
  // "Inter Bold · 64pt · 2 words"): tiny bold bursts dead-center.
  burst: {
    template: "burst",
    fontFamily: "Archivo Black",
    fontSize: 0.056,
    fontWeight: 800,
    karaoke: false,
    animation: "pop",
    uppercase: true,
    textColor: "#ffffff",
    activeColor: "#ffffff",
    activeBgColor: "",
    strokeColor: "#000000",
    strokeWidth: 0.12,
    shadow: true,
    verticalPosition: 0.5,
    maxWordsPerLine: 3,
    highlightKeywords: false,
    accentColor: "#2dd4a0",
    autoEmoji: false,
    twoTone: false,
    boxColor: "",
  },
  hormozi: {
    template: "hormozi",
    fontFamily: "Archivo Black",
    fontSize: 0.06,
    fontWeight: 800,
    karaoke: true,
    animation: "pop",
    uppercase: true,
    textColor: "#ffffff",
    activeColor: "#ffd400",
    activeBgColor: "",
    strokeColor: "#000000",
    strokeWidth: 0.2,
    shadow: true,
    verticalPosition: 0.68,
    maxWordsPerLine: 3,
    highlightKeywords: false,
    accentColor: "#ffd400",
    autoEmoji: false,
    twoTone: false,
    boxColor: "",
  },
  clean: {
    template: "clean",
    fontFamily: "Inter",
    fontSize: 0.046,
    fontWeight: 700,
    karaoke: true,
    animation: "pop",
    uppercase: false,
    textColor: "#ffffff",
    activeColor: "#7c5cff",
    activeBgColor: "",
    strokeColor: "#000000",
    strokeWidth: 0.08,
    shadow: true,
    verticalPosition: 0.74,
    maxWordsPerLine: 4,
    highlightKeywords: false,
    accentColor: "#7c5cff",
    autoEmoji: false,
    twoTone: false,
    boxColor: "",
  },
  pop: {
    template: "pop",
    fontFamily: "Archivo Black",
    fontSize: 0.054,
    fontWeight: 800,
    karaoke: true,
    animation: "pop",
    uppercase: true,
    textColor: "#ffffff",
    activeColor: "#0c0e13",
    activeBgColor: "#2dd4a0",
    strokeColor: "#000000",
    strokeWidth: 0.14,
    shadow: true,
    verticalPosition: 0.7,
    maxWordsPerLine: 3,
    highlightKeywords: false,
    accentColor: "#2dd4a0",
    autoEmoji: false,
    twoTone: false,
    boxColor: "",
  },
  // Kinetic typography: one big word at a time, dead-center on a clean
  // background, scaling/typing in for punch. Seen across the fast-cut
  // reference reels — a single dominant word per beat drives the pacing.
  kinetic: {
    template: "kinetic",
    fontFamily: "Archivo Black",
    fontSize: 0.075,
    fontWeight: 800,
    karaoke: true,
    animation: "typewriter",
    uppercase: true,
    textColor: "#ffffff",
    activeColor: "#ffd400",
    activeBgColor: "",
    strokeColor: "#000000",
    strokeWidth: 0.12,
    shadow: true,
    verticalPosition: 0.46,
    maxWordsPerLine: 1,
    highlightKeywords: false,
    accentColor: "#ffd400",
    autoEmoji: false,
    twoTone: false,
    boxColor: "",
  },
};

export const TEMPLATE_LABELS: Record<CaptionTemplateId, string> = {
  reels: "Reels Clean",
  burst: "Center Burst",
  hormozi: "Hormozi Bold",
  clean: "Minimal Karaoke",
  pop: "Chip Pop",
  kinetic: "Kinetic",
};
